server.port=${PORT:8080}
spring.data.mongodb.uri=mongodb+srv://sattva_admin:Sattva2025@sattva-admin.zfskhqr.mongodb.net/sattva_db?retryWrites=true&w=majority
jwt.secret=SattvaSecretKey2025VeryLongSecretForJWTTokenGeneration
jwt.expiration=86400000
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=./uploads
razorpay.key.id=rzp_test_Sdof8DuKnjYhGW
razorpay.key.secret=QWZuZEm6QlCF7zxYDR14YYyG
admin.username=admin
admin.password=Sattva2025
cors.allowed-origins=http://localhost:5173,https://sattva-frontend.vercel.app
